-- Loans and savings goals for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists loans (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  loan_name text not null,
  original_amount numeric not null,
  remaining_balance numeric not null,
  monthly_payment numeric not null,
  due_day integer
);

create table if not exists savings_goals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  goal_name text not null,
  target_amount numeric not null,
  current_amount numeric not null default 0
);

alter table loans enable row level security;
alter table savings_goals enable row level security;

create policy "Users can view their own loans"
  on loans for select
  using (auth.uid() = user_id);

create policy "Users can insert their own loans"
  on loans for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own loans"
  on loans for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own loans"
  on loans for delete
  using (auth.uid() = user_id);

create policy "Users can view their own savings goals"
  on savings_goals for select
  using (auth.uid() = user_id);

create policy "Users can insert their own savings goals"
  on savings_goals for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own savings goals"
  on savings_goals for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own savings goals"
  on savings_goals for delete
  using (auth.uid() = user_id);
