-- Body measurements (neck, chest, waist, hips, thighs, arms, calf) for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists body_measurements (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  measurement_type text not null,
  side text,
  value numeric not null,
  log_date date not null
);

alter table body_measurements enable row level security;

create policy "Users can view their own body measurements"
  on body_measurements for select
  using (auth.uid() = user_id);

create policy "Users can insert their own body measurements"
  on body_measurements for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own body measurements"
  on body_measurements for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own body measurements"
  on body_measurements for delete
  using (auth.uid() = user_id);
