-- Credit card tracking for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists credit_cards (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  card_name text not null,
  credit_limit numeric not null
);

create table if not exists card_charges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  card_id bigint not null references credit_cards (id) on delete cascade,
  charge_date date not null,
  description text not null,
  amount numeric not null
);

alter table credit_cards enable row level security;
alter table card_charges enable row level security;

create policy "Users can view their own credit cards"
  on credit_cards for select
  using (auth.uid() = user_id);

create policy "Users can insert their own credit cards"
  on credit_cards for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own credit cards"
  on credit_cards for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own credit cards"
  on credit_cards for delete
  using (auth.uid() = user_id);

create policy "Users can view their own card charges"
  on card_charges for select
  using (auth.uid() = user_id);

create policy "Users can insert their own card charges"
  on card_charges for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own card charges"
  on card_charges for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own card charges"
  on card_charges for delete
  using (auth.uid() = user_id);
