-- Workout exercises for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists workout_exercises (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  workout_id bigint not null references workouts (id) on delete cascade,
  exercise_name text not null,
  sets integer,
  reps integer,
  weight_lbs numeric
);

alter table workout_exercises enable row level security;

create policy "Users can view their own workout exercises"
  on workout_exercises for select
  using (auth.uid() = user_id);

create policy "Users can insert their own workout exercises"
  on workout_exercises for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own workout exercises"
  on workout_exercises for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own workout exercises"
  on workout_exercises for delete
  using (auth.uid() = user_id);
