-- Projects and project subtasks for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists projects (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  project_name text not null,
  icon text,
  status text not null default 'Not Started'
);

create table if not exists project_subtasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  project_id bigint not null references projects (id) on delete cascade,
  title text not null,
  is_complete boolean not null default false
);

alter table projects enable row level security;
alter table project_subtasks enable row level security;

create policy "Users can view their own projects"
  on projects for select
  using (auth.uid() = user_id);

create policy "Users can insert their own projects"
  on projects for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own projects"
  on projects for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own projects"
  on projects for delete
  using (auth.uid() = user_id);

create policy "Users can view their own project subtasks"
  on project_subtasks for select
  using (auth.uid() = user_id);

create policy "Users can insert their own project subtasks"
  on project_subtasks for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own project subtasks"
  on project_subtasks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own project subtasks"
  on project_subtasks for delete
  using (auth.uid() = user_id);
