-- Appointments widget for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  appointment_date date not null,
  time_label text not null,
  location text,
  category text not null default 'Other'
);

alter table appointments enable row level security;

create policy "Users can view their own appointments"
  on appointments for select
  using (auth.uid() = user_id);

create policy "Users can insert their own appointments"
  on appointments for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own appointments"
  on appointments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own appointments"
  on appointments for delete
  using (auth.uid() = user_id);
