-- Subscription tracking for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  subscription_name text not null,
  amount numeric not null,
  billing_cycle text not null default 'Monthly',
  card_color text not null default 'peach'
);

alter table subscriptions enable row level security;

create policy "Users can view their own subscriptions"
  on subscriptions for select
  using (auth.uid() = user_id);

create policy "Users can insert their own subscriptions"
  on subscriptions for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own subscriptions"
  on subscriptions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
  on subscriptions for delete
  using (auth.uid() = user_id);
