-- Transaction categorization and itemized detail for mochiboard
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

alter table transactions add column if not exists category text;
alter table transactions add column if not exists subcategory text;
alter table transactions add column if not exists vendor text;

create table if not exists transaction_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  transaction_id bigint not null references transactions (id) on delete cascade,
  item_name text not null,
  unit_price numeric not null,
  quantity numeric not null default 1,
  item_total numeric not null
);

alter table transaction_items enable row level security;

create policy "Users can view their own transaction items"
  on transaction_items for select
  using (auth.uid() = user_id);

create policy "Users can insert their own transaction items"
  on transaction_items for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own transaction items"
  on transaction_items for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own transaction items"
  on transaction_items for delete
  using (auth.uid() = user_id);
